podcasts_site/podcasts/urls.py
from django.urls import path

from podcasts.views import views, substring_specification, all_videos, prefix_specification

urlpatterns = [
    path('', views.index, name="index"),
    path('all', all_videos.index, name="index"),
    path('substrings/<int:podcast_id>', substring_specification.index, name='substrings'),
    path('prefixes/<int:podcast_id>', prefix_specification.index, name='prefixes')
]

podcasts_site/podcasts_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('podcasts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

podcasts_site/podcasts/models.py
import datetime
import logging
import os.path

from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models import UniqueConstraint, Q

from podcasts.views import pstdatetimefield

# Create your models here.

VIDEOS_FOLDER_NAME = "videos"
ARCHIVE_FOLDER_NAME = "archives"
RSS_FEED_FOLDER_NAME = 'rss_feeds'
ARCHIVE_FOLDER_PATH = f"{settings.MEDIA_ROOT}/{ARCHIVE_FOLDER_NAME}"

class CronSchedule(models.Model):
    hour = models.IntegerField()
    minute = models.IntegerField()

    def __str__(self):
        return f"scheduler for {self.hour} hour and {self.minute} minutes"

def string_cleaner(name):
    return (name.replace(':', '').replace(' ', '_').replace(',', '').replace("/", "_")
            .replace("%", "").replace(";", "").replace("#", "").replace("?", ""))

class YouTubePodcast(models.Model):
    # class Meta:
    #     constraints = [
    #         UniqueConstraint(name="one_process_in_progress", fields=['being_processed'], condition=Q(being_processed=True))
    #     ]

    name = models.CharField(max_length=1000)
    custom_name = models.CharField(max_length=1000, null=True)
    description = models.CharField(max_length=5000)
    image = models.CharField(max_length=10000, null=True)
    language = models.CharField(max_length=5)
    author = models.CharField(max_length=10000)
    url = models.CharField(max_length=10000)
    when_to_pull = models.TimeField()
    being_processed = models.BooleanField(default=False)
    category = models.CharField(max_length=1000)
    index_range = models.IntegerField(null=True)
    information_last_updated = pstdatetimefield.PSTDateTimeField(
        null=True
    )
    cbc_news = models.BooleanField(default=False)


    @property
    def front_end_when_to_pull(self):
        return self.when_to_pull.strftime("%H:%M:%S")

    @property
    def frontend_name(self):
        return self.name if self.custom_name is None else self.custom_name

    @property
    def url_friendly_name(self):
        if len(self.name.strip()) == 0:
            raise Exception("no name detected")
        return string_cleaner(self.name) if self.custom_name is None else string_cleaner(self.custom_name)

    @property
    def video_file_location(self):
        return f"{settings.MEDIA_ROOT}/{VIDEOS_FOLDER_NAME}/{self.url_friendly_name}"

    @property
    def archive_file_location(self):
        return f"{settings.MEDIA_ROOT}/{ARCHIVE_FOLDER_NAME}/{self.url_friendly_name}"

    @property
    def feed_file_location(self):
        return f"{settings.MEDIA_ROOT}/{RSS_FEED_FOLDER_NAME}/{self.url_friendly_name}.xml"

    @property
    def rss_feed_available(self):
        return len(self.name.strip()) > 0

    @property
    def files_to_delete_available(self):
        return len(self.name.strip()) > 0

    @property
    def http_feed_location(self):
        return f"{settings.XML_AND_VIDEO_FQDN}{settings.MEDIA_URL}{RSS_FEED_FOLDER_NAME}/{self.url_friendly_name}.xml"

    def get_videos(self):
        return list(self.youtubevideo_set.all())

    @property
    def shown_visible_videos_count(self):
        total = self.youtubevideo_set.all().exclude(
                Q(hide=True) | Q(manually_hide=True)
            ).count()
        return 3 if total >= 3 else total

    @property
    def all_videos_count(self):
        return self.youtubevideo_set.all().count()

    @property
    def front_end_get_visible_videos_list(self):
        return self.youtubevideo_set.all().exclude(
                Q(hide=True) | Q(manually_hide=True)
            ).order_by('-identifier_number')

    @property
    def front_end_get_all_videos_list(self):
        return self.youtubevideo_set.all().order_by('-identifier_number')


    def get_video_filenames(self):
        return list(self.youtubevideo_set.all().values_list('filename', flat=True))

    def __str__(self):
        return self.name if self.custom_name is None else self.custom_name

class YouTubePodcastTitleSubString(models.Model):
    class Meta:
        constraints = [
            UniqueConstraint(fields=['podcast', 'priority'], name='unique_podcast_title_substring_priority')
        ]

    title_substring = models.CharField(max_length=1000, default=None, null=True)
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    priority = models.IntegerField(default=None)

    def __str__(self):
        return f"{self.podcast.frontend_name} substring {self.title_substring}"

# class YouTubePodcastTimestampPriority(models.Model):
#     class Meta:
#         constraints = [
#             UniqueConstraint(fields=['podcast', 'priority'], name='unique_podcast_timestamp_priority')
#         ]
#     timestamp = PSTDateTimeField()
#     podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
#     priority = models.IntegerField(default=None)
#
#     def __str__(self):
#         return f"{self.podcast.frontend_name} timestamp {self.timestamp}"

class YouTubePodcastTitlePrefix(models.Model):
    class Meta:
        constraints = [
            UniqueConstraint(fields=['podcast', 'priority'], name='unique_podcast_title_prefix_priority')
        ]

    title_prefix = models.CharField(max_length=1000, default=None, null=True)
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    priority = models.IntegerField(default=None)

    def __str__(self):
        return f"{self.podcast.frontend_name} prefix {self.title_prefix}"

class YouTubeVideo(models.Model):

    video_id = models.CharField(max_length=1000, unique=True)
    filename = models.CharField(max_length=1000)
    original_title = models.CharField(max_length=1000)
    description = models.CharField(max_length=5000)
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    date = pstdatetimefield.PSTDateTimeField()
    identifier_number = models.PositiveBigIntegerField()
    grouping_number = models.IntegerField()
    url = models.CharField(max_length=10000, unique=True)
    extension = models.CharField(max_length=100)
    image = models.CharField(max_length=10000, null=True)
    size = models.PositiveBigIntegerField()
    hide = models.BooleanField(default=False)
    manually_hide = models.BooleanField(default=False)
    duration = models.PositiveBigIntegerField()
    file_not_found = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        if self.is_present():
            fs = FileSystemStorage()
            fs.delete(self.get_file_location)
        with open(self.podcast.archive_file_location, 'w') as f:
            for video in self.podcast.get_videos():
                if video.video_id != self.video_id:
                    f.write(f"youtube {video.video_id}\n")
        super(YouTubeVideo, self).delete(*args, **kwargs)

    @property
    def get_title(self):
        if self.original_title[:len(self.podcast.frontend_name)] == self.podcast.frontend_name:
            # needed cause if the episode title's prefix is the same as the podcast name, Apple Podcasts takes it upon
            # itself to cut down the episode name on the app
            return f"Ep - {self.original_title}"
        return self.original_title

    @property
    def get_location(self):
        return f"{settings.XML_AND_VIDEO_FQDN}{settings.MEDIA_URL}{VIDEOS_FOLDER_NAME}/{self.podcast.url_friendly_name}/{self.filename}"

    @property
    def get_file_location(self):
        return f'{self.podcast.video_file_location}/{self.filename}'

    @property
    def get_front_end_duration(self):
        return f"{datetime.timedelta(seconds=self.duration)}"

    def is_present(self):
        return os.path.exists(self.get_file_location)

    @property
    def front_end_name(self):
        return f'{self.date.pst.strftime("%a %Y-%b %d %I:%M %p %Z")} {self.get_front_end_duration} - {self.original_title}'

    def __str__(self):
        return f"{self.date.pst} {self.podcast}: {self.original_title}"

class PodcastVideoGrouping(models.Model):
    grouping_number = models.IntegerField()
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    podcast_video = models.ForeignKey(YouTubeVideo, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.grouping_number} grouping for {self.podcast.frontend_name}"

class LoggingFilePath(models.Model):
    error_file_path = models.CharField(
        max_length=500,
        default=None,
        null=True
    )
    warn_file_path = models.CharField(
        max_length=500,
        default=None,
        null=True
    )
    debug_file_path = models.CharField(
        max_length=500,
        default=None,
        null=True
    )

class VideoWithNewDateFormat(models.Model):
    video_title = models.CharField(
        max_length=10000
    )
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)

    def __str__(self):
        return f"Error [{self.video_title}] in podcast {self.podcast}"


class WarnStreamHandlerRecord(models.Model):
    message = models.CharField(
        max_length=10000
    )
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    video_id = models.CharField(
        max_length=100,
        default=None,
        null=True
    )
    def __str__(self):
        return f"Error [{self.message}] in podcast {self.podcast}"

class TroubleRecord(models.Model):
    message = models.CharField(
        max_length=10000
    )
    levelno = models.IntegerField(
        default=logging.WARNING
    )
    video_unavailable = models.BooleanField(
        null=True
    )
    podcast = models.ForeignKey(YouTubePodcast, on_delete=models.CASCADE)
    video_id = models.CharField(
        max_length=100,
        default=None,
        null=True
    )
    def __str__(self):
        return f"Error [{self.message}] in podcast {self.podcast}"

podcasts_site/podcasts/views/Gmail.py
import os.path
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.conf import settings

from podcasts.views.setup_logger import Loggers


class Gmail:

    def __init__(self, from_email=None, password=None, smtp='smtp.gmail.com', port=587, max_number_of_retries=5):
        """
        initialized the gmail object for a gmail account

        Keyword Argument
        from_email -- the email address to log into
        password -- the password for the email to log into
        smtp -- the server that hosts the smptlib server for gmail
        port -- the port for the smptlib server for gmail
        max_number_of_retries -- the maximum number of times to try opening and closing the connection to the smptlib
         server as well as sending the email
        """
        self.logger = Loggers.get_logger("youtube_dlp")
        self.connection_successful = False
        number_of_retries = 0
        if from_email is None:
            from_email = settings.GMAIL_USERNAME
        if password is None:
            password = settings.GMAIL_PASSWORD
        self.from_email = from_email
        self.max_number_of_retries = max_number_of_retries
        while not self.connection_successful and number_of_retries < max_number_of_retries:
            try:
                self.server = smtplib.SMTP(f'{smtp}:{port}')
                self.logger.info(f"[Gmail __init__()] setup smptlib server connection to {smtp}:{port}")
                self.server.connect(f'{smtp}:{port}')
                self.logger.info("[Gmail __init__()] smptlib server connected")
                self.server.ehlo()
                self.logger.info("[Gmail __init__()] smptlib server ehlo() successful")
                self.server.starttls()
                self.logger.info("[Gmail __init__()] smptlib server ttls started")
                self.logger.info(f"[Gmail __init__()] Logging into account {from_email}")
                self.server.login(from_email, password)
                self.logger.info(f"[Gmail __init__()] login to email {from_email} successful")
                self.connection_successful = True
                self.error_message = None
            except Exception as e:
                number_of_retries += 1
                self.logger.error(f"[Gmail __init__()] experienced following error when initializing.\n{e}")
                self.error_message = f"{e}"

    def send_email(self, subject, body, to_email, to_name, from_name="podcasts site", attachments=None):
        """
        send email to the specified email address

        Keyword Argument
        subject -- the subject for the email to send
        body - -the body of the email to send
        to_email -- the email address to send the email to
        to_name -- the name of the person to send the email to
        from_name -- the name to assign to the from name field
        attachment -- the logs to attach to the email if applicable

        Return
        Bool -- true or false to indicate if email was sent successfully
        error_message -- None if success, otherwise, returns the error experienced
        """
        if self.connection_successful:
            number_of_retries = 0
            while number_of_retries < self.max_number_of_retries:
                try:
                    msg = MIMEMultipart()
                    msg['From'] = from_name + " <" + self.from_email + ">"
                    msg['To'] = to_name + " <" + to_email + ">"
                    msg['Subject'] = subject
                    if body:
                        msg.attach(MIMEText(body))

                    if attachments is not None:
                        for attachment in attachments:
                            if os.path.exists(attachment):
                                try:
                                    self.logger.info("trying to attach {}".format(attachment))
                                    package = open(attachment, 'rb')
                                    payload = MIMEBase('application', 'octet-stream')
                                    payload.set_payload(package.read())
                                    encoders.encode_base64(payload)
                                    payload.add_header('Content-Disposition', "attachment; filename={}".format(attachment))
                                    msg.attach(payload)
                                    self.logger.info("{} has been attached".format(attachment))
                                except Exception as e:
                                    self.logger.info(f"{attachment} could not be attached. Error: {e}")
                    self.logger.info(f"[Gmail send_email()] sending email to {to_email}")
                    self.server.send_message(from_addr=self.from_email, to_addrs=to_email, msg=msg)
                    return True, None
                except Exception as e:
                    self.logger.info(f"[Gmail send_email()] unable to send email to {to_email} due to error.\n{e}")
                    number_of_retries += 1
                    self.error_message = f"{e}"
        return False, self.error_message

    def close_connection(self):
        """
        Closes connection to smptlib server

        Return
        Bool -- true or false to indicate if email was sent successfully
        error_message -- None if success, otherwise, returns the error experienced
        """
        if self.connection_successful:
            number_of_retries = 0
            while number_of_retries < self.max_number_of_retries:
                try:
                    self.logger.info("[Gmail close_connection()] closing connection to smtplib server")
                    self.server.close()
                    self.logger.info("[Gmail close_connection()] connection to smtplib server closed")
                    return True, None
                except Exception as e:
                    self.logger.error(
                        "[Gmail close_connection()] experienced following error when attempting "
                        f"to close connection to smtplib server.\n{e}"
                    )
                    number_of_retries += 1
                    self.error_message = f"{e}"
        return False, self.error_message

podcasts_site/podcasts/views/all_videos.py
from django.http import HttpResponse
from django.template import loader

from podcasts.views.showing_videos import showing_videos


# Create your views here.
def index(request):
    return HttpResponse(
        loader.get_template("podcasts/all_videos.html")
        .render(
            showing_videos(request), request
        )
    )

podcasts_site/podcasts/views/get_thumbnails.py
def get_thumbnails(information):
    thumbnail = information.get('thumbnail', None)
    if thumbnail is None:
        pass
    if ".png" in thumbnail:
        return thumbnail[:thumbnail.index(".png") + 4]
    elif ".jpg" in thumbnail:
        return thumbnail[:thumbnail.index(".jpg") + 4]
    else:
        return None

podcasts_site/podcasts/templates/podcasts/all_videos.html
<a href="/" >Home</a> | <a href="/all" >All</a><br>

<form method="post">
    {% csrf_token %}
    <label>Hour:</label><input type="number" name="hour" value="{{ cron_schedule.hour }}">
    <label>Minute:</label><input type="number" name="minute" value="{{ cron_schedule.minute }}">
    <button name="action" value="update_cron" type="submit">Update Cron Time</button>
</form>
<form method="post">
    {% csrf_token %}
    <label>URL:</label><input type="text" name="url">
    <label>Number of Past Items to Process:</label><input type="number" name="index_range">
    <label>When To Pull: </label><input type="time" name="when_to_pull" required><br><br>
    <button name="action" value="Create" type="submit">Create</button>
</form>

{%  for podcast in podcasts %}
    <form method="post">
        {% csrf_token %}
        {% if podcast.image %}
            <img src="{{ podcast.image }}" width="200">
        {%  endif %}
        <h1>{{ podcast }}</h1>
        <input type="number" name="id" value="{{ podcast.id }}" hidden>
        <label>Name:</label><input type="text" name="name" value="{{ podcast.frontend_name }}">
        <label>URL:</label><input type="text" name="url" value="{{ podcast.url }}"> <br>
        <label>Number of Past Items to Process: </label><input type="number" name="index_range" value="{{ podcast.index_range }}"> |
        <label>When To Pull: </label><input type="time" name="when_to_pull" value="{{ podcast.front_end_when_to_pull }}" required><br><br>
        <label>CBC News: </label><input type="checkbox" name="cbc_news" {% if podcast.cbc_news %} checked {%  endif %}><br>
        <label>Description</label>{{ podcast.description|safe|linebreaks }}
        <button name="action" value="Update" type="submit">Update</button>
        <button name="action" value="Reset" type="submit">Reset</button>
        <button name="action" value="Delete" type="submit">Delete</button>
    </form>
    <a href="/substrings/{{ podcast.id }}">Specify Substrings</a><br>
    {%  for substring in podcast.youtubepodcasttitlesubstring_set.all %}
        <p>{{ substring.title_substring }}</p>
    {%  endfor %}
    <a href="/prefixes/{{ podcast.id }}">Specify Prefixes</a><br>
    {%  for prefix in podcast.youtubepodcasttitleprefix_set.all %}
        <p>{{ prefix.title_prefix }}</p>
    {%  endfor %}
    {%  if podcast.rss_feed_available %}
        <a href="{{ podcast.http_feed_location }}" target="_blank">RSS Feed</a><br>
    {%  endif %}
    {%  if podcast.all_videos_count > 0 %}
        <h2>Videos</h2>
        {{ podcast.all_videos_count }} Videos<br>
        {%  for video in podcast.front_end_get_all_videos_list %}
            <form method="post">
                {% csrf_token %}
                <input type="number" name="video_id" value="{{ video.id }}" hidden><button name="action" value="delete_video" type="submit">Delete Video</button>
                <a href="{{video.get_location}}" target="_blank">{{ video.front_end_name }}</a> - <a href="{{ video.url }}" target="_blank">YouTube Link</a>
                {% if video.hide %}
                    <label>Automatically Hidden</label>
                {%  else %}
                    <label>Automatically Visible</label>
                {%  endif %}
                {% if video.manually_hide %}
                    <button name="action" value="Unhide" type="submit">Unhide</button>
                {%  else %}
                    <button name="action" value="Hide" type="submit">Hide</button>
                {%  endif %}
                <br>
            </form>
        {%  endfor %}
    {%  endif %}
    <br><br>

{%  endfor %}

podcasts_site/podcasts/templates/podcasts/index.html
<a href="/" >Home</a> | <a href="/all" >All</a><br>

<form method="post">
    {% csrf_token %}
    <label>Hour:</label><input type="number" name="hour" value="{{ cron_schedule.hour }}">
    <label>Minute:</label><input type="number" name="minute" value="{{ cron_schedule.minute }}">
    <button name="action" value="update_cron" type="submit">Update Cron Time</button>
</form>
<form method="post">
    {% csrf_token %}
    <label>URL:</label><input type="text" name="url">
    <label>Number of Past Items to Process:</label><input type="number" name="index_range">
    <label>When To Pull: </label><input type="time" name="when_to_pull" required><br><br>
    <button name="action" value="Create" type="submit">Create</button>
</form>

{%  for podcast in podcasts %}
    <form method="post">
        {% csrf_token %}
        {% if podcast.image %}
            <img src="{{ podcast.image }}" width="200">
        {%  endif %}
        <h1>{{ podcast }}</h1>
        {%  if podcast.being_processed %}
            <b>Being Processed</b>
        {%  endif %}
        <input type="number" name="id" value="{{ podcast.id }}" hidden>
        <label>Name:</label><input type="text" name="name" value="{{ podcast.frontend_name }}">
        <label>URL:</label><input type="text" name="url" value="{{ podcast.url }}"> <br>
        <label>Number of Past Items to Process: </label><input type="number" name="index_range" value="{{ podcast.index_range }}"> |
        <label>When To Pull: </label><input type="time" name="when_to_pull" value="{{ podcast.front_end_when_to_pull }}" required><br><br>
        <label>CBC News: </label><input type="checkbox" name="cbc_news" {% if podcast.cbc_news %} checked {%  endif %}><br>
        <label>Description</label>{{ podcast.description|safe|linebreaks }}
        <button name="action" value="Update" type="submit">Update</button>
        <button name="action" value="Reset" type="submit">Reset</button>
        <button name="action" value="Delete" type="submit">Delete</button>
    </form>
    <a href="/substrings/{{ podcast.id }}">Specify Substrings</a><br>
    {%  for substring in podcast.youtubepodcasttitlesubstring_set.all %}
        <p>{{ substring.title_substring }}</p>
    {%  endfor %}
    <a href="/prefixes/{{ podcast.id }}">Specify Prefixes</a><br>
    {%  for prefix in podcast.youtubepodcasttitleprefix_set.all %}
        <p>{{ prefix.title_prefix }}</p>
    {%  endfor %}
    {%  if podcast.rss_feed_available %}
        <a href="{{ podcast.http_feed_location }}" target="_blank">RSS Feed</a><br>
    {%  endif %}
    {%  if podcast.shown_visible_videos_count > 0 %}
        <h2>Videos</h2>
        {{ podcast.shown_visible_videos_count }} / {{ podcast.all_videos_count }} Videos<br>
        {%  for video in podcast.front_end_get_visible_videos_list|slice:":3" %}
            {% if not video.hide and not video.manually_hide %}
                <form method="post">
                    {%  csrf_token %}
                    <input type="number" name="video_id" value="{{ video.id }}" hidden>
                    <button name="action" value="delete_video" type="submit">Delete Video</button>
                    <a href="{{video.get_location}}" target="_blank">{{ video.front_end_name }}</a> - <a href="{{ video.url }}" target="_blank">YouTube Link</a><br>
                    {% if video.hide %}
                        <label>Automatically Hidden</label>
                    {%  else %}
                        <label>Automatically Visible</label>
                    {%  endif %}
                    {% if video.manually_hide %}
                        <button name="action" value="Unhide" type="submit">Unhide</button>
                    {%  else %}
                        <button name="action" value="Hide" type="submit">Hide</button>
                    {%  endif %}
                    <br>
                </form>
            {% endif %}
        {%  endfor %}
    {%  endif %}
    <br><br>
{%  endfor %}

podcasts_site/podcasts/templates/podcasts/prefix_specification.html
<a href="/">Home</a><br>
<form method="post">
    {%  csrf_token %}
    <label>Prefix:</label><input type="text" name="title_prefix" required>
    <label>Priority</label><input type="number" name="priority" required>
    <button name="action" value="Create" type="submit">Create</button>
</form>

{%  for prefix in prefixes %}
    <form method="post">
    {% csrf_token %}
    <input type="number" name="id" value="{{ prefix.id }}" hidden>
    <label>Prefix:</label><input type="text" name="title_prefix" value="{{ prefix.title_prefix }}">
    <label>Priority</label><input type="number" name="priority" value="{{ prefix.priority }}">
    <button name="action" value="Update" type="submit">Update</button>
    <button name="action" value="Delete" type="submit">Delete</button>
    </form>
{%  endfor %}

podcasts_site/podcasts/templates/podcasts/substring_specification.html
<a href="/">Home</a><br>
<form method="post">
    {%  csrf_token %}
    <label>Substring:</label><input type="text" name="title_substring" required>
    <label>Priority</label><input type="number" name="priority" required>
    <button name="action" value="Create" type="submit">Create</button>
</form>

{%  for substring in substrings %}
    <form method="post">
    {% csrf_token %}
    <input type="number" name="id" value="{{ substring.id }}" hidden>
    <label>Substring:</label><input type="text" name="title_substring" value="{{ substring.title_substring }}">
    <label>Priority</label><input type="number" name="priority" value="{{ substring.priority }}">
    <button name="action" value="Update" type="submit">Update</button>
    <button name="action" value="Delete" type="submit">Delete</button>
    </form>
{%  endfor %}